datamodule:
  root: D:\My projects\audio classification speech commands\
  batch_size: 64
  n_fft: 200
  pin_memory: False # True if gpu

model:
  num_classes: 35
  dropout: 0.1
  lr: 0.001

logger:
  save_dir: tb_logs
  name: alexnet_logs

trainer:
  max_epochs: 20
  accelerator: auto
  devices: 1
  num_nodes: 1
  # accelerator: gpu
  # gpus: 1