datamodule:
  root: /kaggle/working/
  batch_size: 128
  n_fft: 200
  pin_memory: True # True if gpu

model:
  num_classes: 35
  dropout: 0.1
  lr: 0.001
  optim_configs:
    weight_decay: 0.0001

logger:
  save_dir: tb_logs
  name: alexnet_logs

trainer:
  max_epochs: 10
  accelerator: auto