datamodule:
  root: /kaggle/working/
  batch_size: 64
  n_fft: 200
  pin_memory: True # True if gpu

model:
  num_classes: 35
  dropout: 0.1
  lr: 0.001

logger:
  save_dir: tb_logs
  name: alexnet_logs

trainer:
  max_epochs: 20
  accelerator: auto